project:
  type: website
  output-dir: docs

website:
  title: "humzaakhan.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Humza Khan
      - href: workingpapers.qmd
        text: Working Papers
      - href: Humza Khan CV.pdf
        text: CV
      - href: assignment2.qmd
        text: Assignment 2
      - href: assignment3.qmd
        text: Assignment 3
      - href: assignment4.qmd
        text: Assignment 4
      - href: assignment5.qmd
        text: Assignment 5

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual